Implement Chart for keycloak
aservo/charts pull request #2
Opened 2021-11-12 06:46 UTC by brettaufheber

First draft of an umbrella Helm chart for Keycloak that supports realm customization.

2021-11-15 13:19 UTC, pathob requested changes
Danke @brettaufheber , sehr schöner PR. Die paar Kommentare würde ich gerne noch angehen und dann kann das neue Keycloak Umbrella Chart hoffentlich bald an den Start gehen :)

2021-11-15 13:19 UTC, pathob commented on charts/keycloak-umbrella/templates/secret-env.yaml
> +  namespace: {{ .Release.Namespace }}
Dito.

2021-11-15 13:19 UTC, pathob commented on charts/keycloak-umbrella/templates/config-env.yaml
> +  annotations:
Hinsichtlich Annotations und Labels finde ich das Keycloak Chart nicht so gut. `statefulset*` ist jetzt auf jeden Fall nicht mehr richtig, aber ich würde es jetzt auch nicht `deployment*` nennen. Üblicher ist aus meiner Erfahrung, für das Statefulset oder das Deployment einfach nur `annotations` und `labels` zu haben, und für Pods gibt's die dann nochmal mit `pod*`. Bitnami macht das bspw. so, siehe https://github.com/bitnami/charts/blob/17fd9b9819a1091ff83b9b466976a664f13b932b/bitnami/postgresql/values.yaml#L565

2021-11-15 19:13 UTC, brettaufheber commented on charts/keycloak-umbrella/templates/config-env.yaml
> +  annotations:
Related to this point, there is also a bug that causes an empty "annotations" object.

2021-11-15 19:21 UTC, brettaufheber commented
The curl calls now use the "--fail" argument to cause an error on container level if a 400/500 status code occurs.

2021-11-15 19:25 UTC, brettaufheber commented
I've fixed all of the problems described at this time.

2021-11-17 07:13 UTC, pathob approved these changes

2021-11-17 07:14 UTC, merged